### PR TITLE
Rename lineage.dependencies to exthm.dependencies

### PR DESCRIPTION
**Pull request by nekojackie**

### CODE REVIEW

**Review by SebaUbuntu — APPROVED** [review]
LGTM

**Comment by Foxtrot47** [comment]
+69

**Comment by ghost** [comment]
+1

**Comment by Maitreya29** [comment]
Tested. Built fine, booted and functioned as expected. LGTM.

**Comment by bayasdev** [comment]
+4.20

**Comment by xSylla** [comment]
After this change, the SystemUI crash and I got kernel panic, please gibbe solution or fix it

**Comment by Firmank123** [comment]
a

**Comment by ghost** [comment]
GAMING MODE LINEAGE OS GO 🤯🤯🤯🤯🤯🤯🤯🤯

**Comment by xAbdaziz** [comment]
after this change i got 69x fps in pubg, LGTM

**Comment by Foxtrot47** [comment]
> GAMING MODE LINEAGE OS GO 🤯🤯🤯🤯🤯🤯🤯🤯

Sir you forgot to add gaming mode sir.

**Comment by ghost** [comment]
> Sir you forgot to add gaming mode sir.

he will make commit to track exthmui gaming mode on LOS 😼

**Pull request closed without merging**
